version: 1

disable_existing_loggers: False

# set the log format
formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(filename)s - %(lineno)s - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'

handlers:
  # log to screen
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple

  error_handler:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: simple
    filename: logs/error.log
    maxBytes: 10485760 # 10MB
    backupCount: 5
    encoding: "utf8"
    mode: a

  info_handler:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: simple
    filename: logs/info.log
    maxBytes: 10485760 # 10MB
    backupCount: 5
    encoding: "utf8"
    mode: a

loggers:
  video:
    level: DEBUG
    handler: [console, error_handler]
    propagate: true

root:
  level: DEBUG
  handlers: [console, info_handler, error_handler]
  propagate: true
